name: new_app
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev.
# Remove this line if you wish to publish to pub.dev.
publish_to: 'none'

# Defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Adds the Cupertino Icons font to your application for iOS style icons.
  cupertino_icons: ^1.0.6
  sliding_clipped_nav_bar: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package provides a set of recommended lints for good coding practices.
  flutter_lints: ^3.0.0

flutter:
  # Ensures that the Material Icons font is included with your application.
  uses-material-design: true

  # To add assets to your application, specify the assets directory here.
  assets:
    - assets/
  # Example of adding images:
  # - images/a_dot_ham.jpeg

  # To add custom fonts to your application, list them here.
  # Example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
